### ISSUE TITLE
Write default config to file.

### ISSUE THREAD

**Issue by CrazyBonze** [willkg/everett#136]
Looking for an alternative to ConfigParser with more options lead me to this library but it is missing one feature I often use. With ConfigParser, if you have a config set up in code as a default config you can write it to disk as a default configuration. An example here in the [documentation](https://docs.python.org/3/library/configparser.html#quick-start). Would this be within the scope of this library to add this? Both ConfigObj and PyYAML have the ability to go from a python representation to there respective config formats.

**Comment by willkg** [comment]
I think this is definitely possible if you're creating an Everett component that captures all your configuration. For example, something like this:

```python
class Settings(RequiredConfigMixin):
    required_config = ConfigOptions()
    required_config.add_option("logging_level", default="INFO", doc="Logging level")
    required_config.add_option("host_id", default="none", doc="host id for this node")
```

You can call `get_required_config()` on that to get all the options and then use that to populate a ConfigParser and write it to disk. That's how I'm logging configuration at startup now:

https://github.com/mozilla-services/antenna/blob/81eaad78fbaa1947ec31cab11b06aeb4b74c6c28/antenna/app.py#L115-L129

Maybe it's interesting to add a classmethod to the source classes that takes a class that subclasses `RequiredConfigMixin` and a list of namespaces and an output file name and dumps the basic file to disk. Having said that, this doesn't work if you're building Everett component trees because the configuration "figures itself out" at runtime when the components are instantiated.

What do you think about this? Does it help at all?

**Comment by willkg** [comment]
@CrazyBonze ^^^ ?

**Comment by CrazyBonze** [comment]
Sorry i didnt reply back, your comment allowed me to find a solution. Thanks for the help.

**Comment by willkg** [comment]
Thank you!
