### ISSUE TITLE
clarify expected config source behavior on error

### ISSUE THREAD

**Issue by petri** [willkg/everett#53]
What is a config source expected to do when there is an error?

Should the source always return NO_VALUE in such a case, or is raising some exception ok?

**Comment by willkg** [comment]
It depends on the error.

For example, with `ConfigDictEnv`, if the error is a `KeyError`, then that error indicates the key doesn't exist in that environment and therefore it should return `NO_VALUE`.

If the error was something else, then that's either a bug in the environment code which should percolate to the top or it's a configuration problem that the user needs to fix which should also percolate to the top. In Python 2, those errors would just percolate as is. In Python 3, Everett will throw a `ConfigurationError` because Python 3 chains exceptions so you get all the information.

I'll clarify the docs.

Does that answer your questions?

**Comment by willkg** [comment]
I added some clarification in f6c56907.

**Comment by petri** [comment]
Thanks!
