### ISSUE TITLE
Document usage of parser=pathlib.Path

### ISSUE THREAD

**Issue by pjz** [willkg/everett#55]
It would be nice if there was a way to specify that values had to be valid, extant, readable files.  I think it's a common thing to want, hence my suggestion of adding it as a feature.

**Comment by willkg** [comment]
I probably won't implement this until I need it, but I'd welcome a PR from someone.

**Comment by willkg** [comment]
@pjz Is this something you want to implement? If not, then this will probably hang out until I need it.

**Comment by willkg** [comment]
@pjz Is this something you still want and are able to implement? If not, I'm going to nix it.

**Comment by pjz** [comment]
Yeah, I'll take a swing at it soon; I think it'd be useful.

**Comment by willkg** [comment]
Let me know if you need any help!

**Comment by pjz** [comment]
Right now all the parser names are types which also are casting-type functions, and there's of course no 'filename' type, so should I use `file` such that `parser=file` would be how it was used? and then special-case it like you do with ` bool` ?  or should I make like an `everett.parser.filename` class so it would be used via `parser=everett.parser.filename` ?

**Comment by pjz** [comment]
Ah, yes indeed.  That's quite helpful! PR incoming.

**Comment by pjz** [comment]
okay, the docs you point to say "If the value is not parseable, then it should raise a ValueError." ... is this true? or should it raise an `everett.InvalidValueError` ?

**Comment by willkg** [comment]
The parser needs to raise `ValueError` or something like that. The manager code will catch that (or whatever else your parser raises) and in Python 3 wrap that in an `InvalidValueError` and in Python 2 cry in a corner because Python 2 doesn't have exception chaining:

https://github.com/willkg/everett/blob/07ffdfdde160451baff34cb56b500308f0a579f0/everett/manager.py#L994

So, the docs are correct--the parser should raise a `ValueError` for value errors. The thinking is that parsers are mimicking behavior for `bool` and `int` which raise value errors when handed strings that don't represent values in those spaces.

```
>>> int('foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'foo'
>>> 
```

The filename parser is validating against other kinds of requirements. For better usability, maybe it's better to let the machinery raise whatever errors it raises. For example, if the file doesn't exist, let it raise an `IOError: file doesn't exist`.

Does that seem prudent? Are there better ways to handle this usability-wise?

**Comment by pjz** [comment]
That all makes total sense, and jibes with what I thought was going on - it was when I went to write tests that I ran into the problem.  I wrote a test like:

    with pytest.raises(InvalidValueError):
        config('FOO', parser=ExistingFile('w'))

...which failed because it threw `ValueError` and not the expected `InvalidValueError`.

**Comment by pjz** [comment]
So did I write the tests wrong? or how should this be resolved?

**Comment by willkg** [comment]
@pjz Sorry about that! I don't think I ever got a notification of your last response.

I don't think `config()` should return an open file handle. I'd have to see test code to know whether you're writing tests wrong or not. That's probably better done in a PR.

**Comment by pjz** [comment]
#67 is the PR, including test code.  It's a WIP due to unresolved design issues that you didn't have time to weigh in on a few months ago.

**Comment by pjz** [comment]
Per discussion on #67, consensus seems to be to support parsing by using the (py3) `pathlib` library and doing `parser=pathlib.Path`, which should work with the current code.  There should probably be documentation of this, however.

**Comment by willkg** [comment]
@pjz While this didn't result in code changes, you did a ton of solid work here figuring things out. Thank you!
