### ISSUE TITLE
Optional config options, required on value

### ISSUE THREAD

**Issue by jamielennox** [willkg/everett#97]
Hi, 

I'm looking through the library as it seems to match a lot of how i think about config declaration. I'm wondering if there's a way to do like a conditional required through the config declaration. 

I really like the component model, as i can define these in a shared library for my organization.

What I'm looking for is something like the `RabbitMQComponent` example, but being able to say like `RMQ_PRIORITY_ENABLED` as a variable, and if enabled then host etc is required, if not the section basically gets ignored.

I could see this being used in like a plugin model as well where if like `VARIABLE_TYPE=abcd` then a specific class is loaded that has different required variables. 

Thanks, Enjoying the library so far.

**Comment by willkg** [comment]
I'm not really sure I understand this. Configuration is parsed and validated at use-time. Everett doesn't go through and verify the configuration for a component--you'd have to write code that does that. For example, I think your use-case works fine like this:

```
class RabbitMQComponent(RequiredConfigMixin):
    required_config = ConfigOptions()
    required_config.add_option(
        'enabled',
        doc='Whether this is enabled or not',
        parser=bool,
    )
    required_config.add_option(
        'host',
        doc='RabbitMQ host to connect to'
    )
    required_config.add_option(
        'port',
        default='5672',
        doc='Port to use',
        parser=int
    )
    required_config.add_option(
        'queue_name',
        doc='Queue to insert things into'
    )

    def __init__(self, config):
        # Bind the configuration to just the configuration this
        # component requires such that this component is
        # self-contained.
        self.config = config.with_options(self)
        if self.config['enabled']:
            self.host = self.config('host')
            self.port = self.config('port')
```

Does that make sense? If not, maybe I don't understand what you're trying to do.

**Comment by jamielennox** [comment]
Yea, that's basically my use case. I wrote this out thinking it was an easy feature but then dove a little further into how everything works. 

Basically I wanted a `cache['enabled']` kind of feature that made the cache connection strings required if enabled. 

I see why that's more difficult here. Up to you if you want to consider it a feature request or just close this out.

**Comment by willkg** [comment]
I'll have to think about whether there's a lot of value in having a validator across configuration options and if so, how to specify validation rules that document well and how does it work with subclassing. Seems tricky, but interesting.

This isn't something I can think about soon, but I think it's worth keeping the issue open as a rainy day project for someone.

**Comment by willkg** [comment]
It's been a while since this was opened. I had a talk with a colleague about configuration as a set of steps:

1. acquire and parse values
2. validate configuration

I think Everett addresses the first step. It lets you acquire values from a variety of sources and parses those values from the value in the source into a final value.

Everett doesn't touch the second step at all. There's some minimal type validation for individual values, but generally there is no scaffolding for supporting validation of configuration. I don't think I want to tackle that with this project. I think if someone were interested in validation, they could write a library that sits on top of Everett and experiment with configuration validation there.

Given that, I'm going to close this out.
